### ISSUE TITLE
Communicating directly with a KNX serial gateway

### ISSUE THREAD

**Issue by gabrielruiu** [vapourismo/knx-go#20]
This library currently supports only KNXnet/IP. I am interested in extending the support for my application, which should also be able to directly communicate to serial KNX gateway/devices (which are mounted on a system as a `/dev/tty*` device).

My question is: How would I go about doing that?

I've noticed in the code that the `Socket` interface might be the solution. To just replace the current `TunnelSocket` implementation with one that writes directly to a local serial device. But I'm not sure if it's just as simple as replacing the interface implementaiton. Does the rest of the library exclusively depend on the fact that it is KNXnet/IP?

From you experience with KNX, would this work? Is there anything that needs to be added to correctly send the `[]byte` payloads? Because I see there are some `Pack` and `Unpack` methods that handle enriching and extracting the data). Would something similar need to be done if I want to send directly to a serial device?

**Comment by vapourismo** [comment]
From what I understand, devices that are connected via USB or serially are vastly different from KNXnet/IP devices.

It would be inappropriate to reuse the Socket interface given that the communication doesn't run via sockets.

I would imagine you could reuse the `knx/dpt` for all datapoint type related things. It gets tricky with 
`knx/cemi` because devices might use EMI1 or EMI2 frames which are not the same.

The very first step should be an analysis of how the frames to those devices actually look like.

**Comment by gabrielruiu** [comment]
Thank you for the quick reply. Will investigate further.

**Comment by ferllings** [comment]
@gabrielruiu Did you find a way to use serial with the library?
I'm looking for doing the same.
